### ISSUE TITLE
Basic requirements checklist ✅

### ISSUE THREAD

**Issue by pierozkitwarozki** [pierozkitwarozki/WorkoutPartner#3]
### Requirements list
Order can be random. 

There should be no details on each feature. Link the issue when prepared.
Mark the requirement as done, when the whole feature is working.

- [x] Sign-in/sign-up using basic credentials (email, password). Username is not fitting the application needs.  #4 
- [ ] Sign-in/sign-up using credential providers (Meta, Google, Apple) #4 
- [x] Exercise addition (these can be used globally later on)
- [ ] Workout addition and tracking
- [ ] Data analysis (single exercises, whole workouts and others)
- [ ] Rest tracking (track rest between exercises when the workout is on and send notification when the rest is over)
